//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollub.EduConfig {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pollub.EduConfig.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EduConfig.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalacja certyfikatu się nie powiodła. Błąd certutil:.
        /// </summary>
        internal static string CertFail {
            get {
                return ResourceManager.GetString("CertFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (C) Politechnika Lubelska 2013.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użycie:
        ///EduConfig.exe [/s] [/?]
        ///
        ///EduConfig automatycznie zainstaluje certyfikat sieci eduroam dodając go do twojego zbioru zaufanych głównych urzędów certyfikacji oraz profil sieciowy. Będzie wymagane podanie nazwy użytkownika i hasła przy pierwszym połączeniu z siecią eduroam.
        ///Oficjalnie obsługiwane są systemy operacyjne z rodziny Windows NT w wersji 6.0 lub nowszej.
        ///
        ///  /s - uruchamia w trybie cichym (bez potwierdzeń, bez komunikatów błędów), zwraca kod błędu przez ERRORLEVEL
        ///  /? - wyświetla te inf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EduConfig automatycznie zainstaluje certyfikat sieci eduroam dodając go do twojego zbioru zaufanych głównych urzędów certyfikacji oraz profil sieciowy. Będzie wymagane podanie nazwy użytkownika i hasła przy pierwszym połączeniu z siecią eduroam. Czy chcesz kontynuować?.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta aplikacja wymaga uprawnień administratora..
        /// </summary>
        internal static string NeedAdmin {
            get {
                return ResourceManager.GetString("NeedAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] plca_cert {
            get {
                object obj = ResourceManager.GetObject("plca_cert", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalacja profilu sieciowego się nie powiodła. Błąd netsh:.
        /// </summary>
        internal static string ProfFail {
            get {
                return ResourceManager.GetString("ProfFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalacja sieci eduroam została zakończona pomyślnie..
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta wersja systemu operacyjnego może nie być obsługiwana. Obsługiwane są jedynie systemy Windows Vista lub nowszy. Czy chcesz kontynuować?.
        /// </summary>
        internal static string SystemNotSupported {
            get {
                return ResourceManager.GetString("SystemNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił nieoczekiwany błąd:.
        /// </summary>
        internal static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;WLANProfile xmlns=&quot;http://www.microsoft.com/networking/WLAN/profile/v1&quot;&gt;
        ///  &lt;name&gt;eduroam&lt;/name&gt;
        ///  &lt;SSIDConfig&gt;
        ///    &lt;SSID&gt;
        ///      &lt;hex&gt;656475726F616D&lt;/hex&gt;
        ///      &lt;name&gt;eduroam&lt;/name&gt;
        ///    &lt;/SSID&gt;
        ///  &lt;/SSIDConfig&gt;
        ///  &lt;connectionType&gt;ESS&lt;/connectionType&gt;
        ///  &lt;connectionMode&gt;auto&lt;/connectionMode&gt;
        ///  &lt;MSM&gt;
        ///    &lt;security&gt;
        ///      &lt;authEncryption&gt;
        ///        &lt;authentication&gt;WPA2&lt;/authentication&gt;
        ///        &lt;encryption&gt;AES&lt;/encryption&gt;
        ///        &lt;useOneX&gt;true&lt;/useOneX&gt;
        ///        &lt;FIPSMode xmlns [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wlan0_eduroam {
            get {
                return ResourceManager.GetString("wlan0_eduroam", resourceCulture);
            }
        }
    }
}
